# Generated by Django 4.2.5 on 2023-09-22 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Seller'}, on_delete=django.db.models.deletion.PROTECT, related_name='seller_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
